### ISSUE TITLE
Aureus Example App is Missing Some Widgets

### ISSUE THREAD

**Issue by offchristianamr** [Astra-Labs/Aureus#71]
Listed below are all the widgets in the aureus.dart file. Those marked with [x] are included in the example app.

Cards — Standard
- [x] StandardCardElement
- [x] StandardBadgeCardElement
- [x] StandardSwitchCardElement
- [x] StandardSelectionCardElement

Cards — Detail
- [x] DetailCardElement
- [x] DetailBadgeCardElement
- [x] DetailCarouselCardElement
- [x] CategoryIconDetailCardElement

Cards — Complex
- [x] ComplexCardElement
- [x] ComplexBadgeCardElement
- [x] ComplexSwitchCardElement

Cards — Grid
- [x] GridCardElement
- [x] GridBadgeCardElement

Info Hierachy
- [x] ArticleViewElement
- [x] TabSubheaderElement
- [x] MissionHeaderElement
- [x] PageHeaderElement
- [x] DividerElement
- [x] DividingHeaderElement

Misc Elements
- [x] ContainerWrapperElement
- [x] FloatingContainerElement
- [x] CompletionCircleElement
- [x] LoadingCircleElement
- [x] ProgressIndicatorElement
- [x] TimerElement
- [x] PulseShadowElement
- [x] EclipseShadowElement

User Input
- [x] Text FieldComponent
- [x] TextViewComponent
- [x] SliderElement

Alert Controllers
- [x] CenteredAlertControllerComponent
- [x] ContentWarningComponent
- [x] BottomActionSheetComponent

Button
- [x] FullWidthButtonElement
- [x] IconButtonElement
- [x] SmolButtonElement
- [x] StandardButtonElement
- [x] StandardIconButtonElement

Collection Views
- [x] DetailCardCarouselComponent
- [x] QuickActionBarComponent

Communication
- [x] MessageBubbleComponent
- [x] NotificationComponent
- [x] SearchBarComponent
- [x] SendFieldComponent
- [x] BlankScreenComponent
- [x] CookieBannerComponent
- [x] ExitBarComponent
- [x] BannerNotificationComponent
- [x] SwitchComponent

Tabbing Bars
- [x] IconTabbingBarComponent
- [x] NavBarComponent
- [x] IteratingTabbingComponent
- [x] SmolTextTabbingBarComponent
- [x] VerticalSideNavBarComponent

Onboarding
- [x] OnboardingDemoView
- [x] OnboardingInformationView
- [x] OnboardingLandingView

Utilities
- [x] DataConsentView
- [x] 2FAVerificationView
- [x] SettingsView
- [x] PasscodeView

Info Hierarchy
- [x] HelpCenterView
- [x] DataDetailView
- [x] CheckboxArticleView

Landing
- [x] LandingPageView
- [x] SignInView
- [x] SplashScreenView

Supporting
- [x] ContainerView

Misc
- [x] PoetryGradientView

SafetyPlan
- [x] SafetyPlanOptInView
- [x] SafetyPlanOptionsView
- [x] SafetyPlanLogInAuditView
- [x] SafetyPlanSettingsView

Tool Library
- [x] ToolDetailView
- [x] ToolNextStepView
- [x] ToolSummaryView
- [x] ToolNavigationCardCarouselView

Tool Templates
- [x] BaseCardToolTemplate
- [x] BagePageToolTemplate

Mini Tools
- [x] CameraInputToolTemplate
- [x] ColorSpectrumToolTemplate
- [x] MapInputToolTemplate
- [x] MicrophoneInputToolTemplate
- [x] PulseInputToolTemplate
- [x] SensoryMapToolTemplate
- [x] SketchToolTemplate
- [x] TimerToolTemplate
- [x] AdaptiveInputSelectionToolTemplate
- [x] AdaptiveInputToolTemplate
- [x] VideoInputToolTemplate

User Input
- [x] DualColumnInputToolTemplate
- [x] InputSummaryToolTemplate
- [x] PromptListUserInputToolTemplate
- [x] SingleInputToolTemplate
- [x] SingleSliderInputToolTemplate
- [x] TriInputToolTemplate
- [x] DatePickerInputToolTemplate
- [x] TimePickerInputToolTemplate

User Selection
- [x] ListViewButtonSelectToolTemplate
- [x] ListViewPickerSelectToolTemplate
- [x] MultiCategoryCardSelectInputToolTemplate
- [x] YesNoButtonSelectToolTemplate
- [x] GridCardSelectToolTemplate

**Comment by codingiswhyicry** [comment]
Some of these are in the Testing Tool on the side bar (this is my bad, I didn't communicate that) so I'm checking them off as done :-)

**Comment by codingiswhyicry** [comment]
Finished audit, pushing new version of example app to FB and GitHub :-)

**Comment by codingiswhyicry** [comment]
That being said, some of these aren't gonna make the cut into the Example App because of the way they're laid out. E.G: VerticalSideNavBar and NavBarComponent all have views that fill the screen and expand fully, and therefore can't be put in a list view. I don't think this is a big deal because the example app is literally made up of these two components, so there's still a reference point.

**Comment by codingiswhyicry** [comment]
Updated on the website, and the codebase. :-)
