### ISSUE TITLE
TEAM QA Issue

### ISSUE THREAD

**Issue by codingiswhyicry** [Astra-Labs/Aureus#77]
For the Astra team @offchristianamr and @taramukund, this is where to drop all of the issues that you find in the Aureus example app before we put it into deep freezer for v.1 launch.

**Comment by codingiswhyicry** [comment]
- The example app on Mobile / Tablet is a little wonky with the Nav Bar, so this needs to be fixed. 
- There is an intermittent issue with the just_audio package. Sometimes it plays the sounds, sometimes it does not. 
- The notifications sometimes do not show if you navigate away from the main tab bar and then back. 
- Data Detail View needs a DividerElement to mimic the Figma file

**Comment by codingiswhyicry** [comment]
- FloatingContainerElements don't always clip around edges, even with the ClipRect mask. This makes some of the elements look rough on scroll.

**Comment by codingiswhyicry** [comment]
- Timer doesn't display an actual time allotment until start is pressed. Makes for bad UX.

**Comment by codingiswhyicry** [comment]
- Sizing needs to take into consideration the SafeArea height with the method size.logicalHeight(). Maybe add a 3rd 'safeHeight' method? I just realized this is why we're getting tiny layout errors on the screens. Oi.

**Comment by codingiswhyicry** [comment]
![Simulator Screen Shot - iPhone 12 mini - 2023-03-03 at 17 18 50](https://user-images.githubusercontent.com/10201992/222867473-e0b29621-6859-4568-9ea5-bf97da0d8b1f.png)

We should center this text in the alert controller, and also reduce the overall padding and or make it dynamic. It's not rough, but a bit excessive.

**Comment by codingiswhyicry** [comment]
Do we really need an 'onCancellation' param for the AlertControllerObject? I don't think people are going to use it that much. I've certainly never used it.

**Comment by codingiswhyicry** [comment]
We're still consistently having an issue with going into a new page, and then coming back to 'no observer registered'. This is a continued issue with the flutter life cycle methods and the notificationMaster class. If you open an incident log flow in Verena and then exit back, you can't actually 'exit' the alert controller screen. AAAAAA

**Comment by offchristianamr** [comment]
- Triggering a notification while one is already on the screen does not reset the notification timer. As a result, triggering a second notification right before the first one disappears will result in the second clearing before the user has time to read it.

**Comment by offchristianamr** [comment]
- Scaling issues with Timer element when viewed on mobile devices.

<img width="606" alt="image" src="https://user-images.githubusercontent.com/48657157/224183745-ba3abddd-a790-4373-a5e7-fd2c1095df64.png">
